---
# This patch sets up the manger container to run Delve and exposes the debug port at
# :40000
# It requires the `remote-debug` controller container built with ubuntu and Delve
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: korifi-controllers-system
  labels:
    app: korifi-controllers-controller-manager
spec:
  template:
    metadata:
      labels:
        app: korifi-controllers-controller-manager
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
      - name: manager
        command:
        - "/dlv"
        args:
        - "--listen=:40000"
        - "--headless=true"
        - "--api-version=2"
        - "exec"
        - "/manager"
        - "--continue"
        - "--accept-multiclient"
        - "--"
        - "--health-probe-bind-address=:8081"
        - "--leader-elect"
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - SYS_PTRACE
