apiVersion: services.cloudfoundry.org/v1alpha1
kind: CFServiceBinding
metadata:
  name: my-service-binding-guid
  namespace: cf
  labels:
    servicebinding.io/provisioned-service: "true"
spec:
  name: my-binding-name
  service:
    apiVersion: services.cloudfoundry.org/v1alpha1
    kind: CFServiceInstance
    name: 7e0dec79-2f4e-43ee-a682-3c3f4b8e7fd1
  secretName: cf-service-credentials-7e0dec79-2f4e-43ee-a682-3c3f4b8e7fd1 # shares the same secret as the UPSI, may be a different secret in the case of managed service bindings
  appRef:
    name: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
