---
apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: RunWorkload
metadata:
  name: 99dcda7d-1fa1-4a91-b437-fbdba20et56y
  namespace: cf
spec:
  GUID: 99dcda7d-1fa1-4a91-b437-fbdba20et56y
  appGUID: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
  command:
  - bundle
  - exec
  - rackup
  - config.ru
  - -p
  - $PORT
  - -o 0.0.0.0
  version: "1"
  health:
    type: http
    port: 8080
    endpoint: /healthz
    timeoutMs: 10000
  instances: 4
  image: ubuntu
  imagePullSecrets:
  - name: image-registry-credentials
  memoryMiB: 50
  diskMiB: 50
  cpuRequestMillicores: 5
  cpuLimitMillicores: 0
  processType: web
