# permissions for end users to view cforgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cforg-viewer-role
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cforgs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cforgs/status
  verbs:
  - get
