apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: korifi-api
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: korifi-api
  strategy: {}
  template:
    metadata:
      labels:
        app: korifi-api
    spec:
      serviceAccountName: system-serviceaccount
      containers:
      - image: cloudfoundry/korifi-api:latest
        name: korifi-api
        ports:
        - containerPort: 9000
          name: web
        resources: {}
        env:
        - name: APICONFIG
          value: "/etc/korifi-api-config"
        - name: TLSCONFIG
          value: "/etc/korifi-tls-config"
        volumeMounts:
        - name: &configname korifi-api-config
          mountPath: /etc/korifi-api-config
          readOnly: true
        - name: &tlsname korifi-tls-config
          mountPath: /etc/korifi-tls-config
          readOnly: true
      volumes:
      - name: *configname
        configMap:
          name: korifi-api-config
      - name: *tlsname
        secret:
          secretName: korifi-api-internal-cert
