apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cf-k8s-api
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-k8s-api
  strategy: {}
  template:
    metadata:
      labels:
        app: cf-k8s-api
    spec:
      serviceAccountName: cf-admin-serviceaccount
      containers:
      - image: cloudfoundry/cf-k8s-api:latest
        name: cf-k8s-api
        ports:
        - containerPort: 9000
          name: web
        resources: {}
        env:
        - name: CONFIG
          value: "/cf_k8s_api_config.yaml"
        volumeMounts:
        - name: &configname cf-k8s-api-config
          mountPath: /cf_k8s_api_config.yaml
          subPath: cf_k8s_api_config.yaml
          readOnly: true
      volumes:
      - name: *configname
        configMap:
          name: cf-k8s-api-config
