# Adds namespace to all resources.
namespace: korifi-api-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: korifi-api-

bases:
- ../cf_roles

resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- rbac

configMapGenerator:
- files:
  - apiconfig/korifi_api_config.yaml
  - apiconfig/role_mappings_config.yaml
  name: config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: cloudfoundry/korifi-api
  newName: cloudfoundry/korifi-api
  newTag: latest

patches:
- path: api_url_patch.yaml
  target:
    group: projectcontour.io
    kind: HTTPProxy
    name: proxy
    version: v1
