apiVersion: v1
kind: Service
metadata:
  labels:
    app: cf-k8s-api
  name: svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: web
    name: web
  selector:
    app: cf-k8s-api
