
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networking-cloudfoundry-org-v1alpha1-cfroute
  failurePolicy: Fail
  name: mcfroute.kb.io
  rules:
  - apiGroups:
    - networking.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cfroutes
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workloads-cloudfoundry-org-v1alpha1-cfapp
  failurePolicy: Fail
  name: mcfapp.kb.io
  rules:
  - apiGroups:
    - workloads.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cfapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workloads-cloudfoundry-org-v1alpha1-cfbuild
  failurePolicy: Fail
  name: mcfbuild.kb.io
  rules:
  - apiGroups:
    - workloads.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cfbuilds
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workloads-cloudfoundry-org-v1alpha1-cfpackage
  failurePolicy: Fail
  name: mcfpackage.kb.io
  rules:
  - apiGroups:
    - workloads.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cfpackages
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workloads-cloudfoundry-org-v1alpha1-cfprocess
  failurePolicy: Fail
  name: mcfprocess.kb.io
  rules:
  - apiGroups:
    - workloads.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cfprocesses
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-workloads-cloudfoundry-org-v1alpha1-cfapp
  failurePolicy: Fail
  name: vcfapp.kb.io
  rules:
  - apiGroups:
    - workloads.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cfapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hnc-x-k8s-io-v1alpha2-subnamespaceanchor
  failurePolicy: Fail
  name: vsubns.kb.io
  rules:
  - apiGroups:
    - hnc.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - subnamespaceanchors
  sideEffects: NoneOnDryRun
