{{- if not .Values.global.containerRegistryServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: {{ .Values.global.rootNamespace }}
  annotations:
    cloudfoundry.org/propagate-service-account: "true"
secrets:
  - name: {{ .Values.global.containerRegistrySecret }}
imagePullSecrets:
  - name: {{ .Values.global.containerRegistrySecret }}
{{- end }}
