#! Is there a way to configure the targetNamespaces list to refer to the namespace in which the delegation resource exists so that we can
#! cascade permissions through HNC? That way we avoid pollution of or outright incompatibility with
#! existing Contour configurations
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: workloads-fallback-delegation
spec:
  delegations:
    - secretName: cf-k8s-workloads-ingress-cert
      targetNamespaces:
        - "*"
