# This patch adds objectSelector to the webhook config
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: mpod.korifi.cloudfoundry.org
  objectSelector:
    matchLabels:
      korifi.cloudfoundry.org/add-stsr-index: "true"
