# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(KIB_CERTIFICATE_NAMESPACE)/$(KIB_CERTIFICATE_NAME)
  name: buildworkloads.ext.cloudfoundry.org
