---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: korifi-kpack-image-builder-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/korifi-controllers-serving-cert'
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: korifi-controllers-webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-korifi-cloudfoundry-org-v1alpha1-kpack-image-builder-finalizer
    failurePolicy: Fail
    name: mcf-kib-finalizer.korifi.cloudfoundry.org
    rules:
      - apiGroups:
          - korifi.cloudfoundry.org
          - kpack.io
        apiVersions:
          - v1alpha1
          - v1alpha2
        operations:
          - CREATE
        resources:
          - buildworkloads
          - builds
    sideEffects: None
