
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kpack.io
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kpack.io
  resources:
  - images/finalizers
  verbs:
  - update
- apiGroups:
  - kpack.io
  resources:
  - images/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfdomains/finalizers
  verbs:
  - update
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfdomains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfroutes/finalizers
  verbs:
  - update
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies/finalizers
  verbs:
  - update
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies/status
  verbs:
  - get
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfbuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfprocesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfprocesses/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfprocesses/status
  verbs:
  - get
  - patch
  - update
