
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfdroplets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfdroplets/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfdroplets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfprocesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfprocesses/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfprocesses/status
  verbs:
  - get
  - patch
  - update
