kpackImageTag: gcr.io/cf-relint-greengrass/cf-k8s-controllers/kpack/beta
clusterBuilderName: cf-kpack-cluster-builder
cfProcessDefaults:
  memoryMB: 1024
  diskQuotaMB: 1024
cfRootNamespace: cf
cfk8s_controller_namespace: cf-k8s-controllers-system
workloads_tls_secret_name: ""
