externalFQDN: localhost
internalPort: 9000

rootNamespace: cf
buildReconciler: kpack-image-builder
defaultLifecycleConfig:
  type: buildpack
  stack: cflinuxfs3
  stagingMemoryMB: 1024
  stagingDiskMB: 1024
packageRegistryBase: localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages
packageRegistrySecretName: image-registry-credentials
defaultDomainName: vcap.me
userCertificateExpirationWarningDuration: 168h
