# The CF Space Manager Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: space-manager
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps
  verbs:
  - get

- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages
  verbs:
  - get

- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfbuilds
  verbs:
  - get

- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfserviceinstances
  verbs:
  - list
  - get

- apiGroups:
    - services.cloudfoundry.org
  resources:
    - cfservicebindings
  verbs:
    - list
