{{- if .Values.global.generateIngressCertificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-workloads-ingress-cert
  namespace: {{ .Values.namespace }}
spec:
  commonName: \*.{{ .Values.global.defaultAppDomainName }}
  dnsNames:
  - \*.{{ .Values.global.defaultAppDomainName }}
  issuerRef:
    kind: Issuer
    name: korifi-controllers-selfsigned-issuer
  secretName: korifi-workloads-ingress-cert
{{- end}}
