apiVersion: v1
kind: Service
metadata:
  labels:
    app: cf-k8s-api
  name: svc
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: web
    name: web
  selector:
    app: cf-k8s-api
