apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: korifi-controllers-workloads-fallback-delegation
  namespace: {{ .Release.Namespace }}
spec:
  delegations:
  - secretName: korifi-workloads-ingress-cert
    targetNamespaces:
    - '*'
