global:
  defaultAppDomainName: vcap.me
  generateIngressCertificates: true

createAdminUser: true

api:
  apiServer:
    url: api.vcap.me
  image: cloudfoundry/korifi-api:latest
  packageRegistry: localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages

controllers:
  taskTTL: 5s
  image: cloudfoundry/korifi-controllers:latest

job-task-runner:
  image: cloudfoundry/korifi-job-task-runner:latest
  jobTTL: 5s

kpack-image-builder:
  image: cloudfoundry/korifi-kpack-image-builder:latest
  packageRegistry: localregistry-docker-registry.default.svc.cluster.local:30050/korifi-controllers/kpack/images
  exampleClusterBuilder:
    create: true
    kpackBuilderRegistry: localregistry-docker-registry.default.svc.cluster.local:30050/cf-relint-greengrass/korifi/kpack/beta

statefulset-runner:
  image: cloudfoundry/korifi-statefulset-runner:latest

contour-router:
  image: cloudfoundry/korifi-contour-router:latest
