adminUserName: cf-admin

global:
  defaultAppDomainName: apps-127-0-0-1.nip.io
  generateIngressCertificates: true
  containerRepositoryPrefix: localregistry-docker-registry.default.svc.cluster.local:30050/
  logLevel: debug

api:
  apiServer:
    url: localhost
  uaaURL: "https://uaa.mel-c.korifi.cf-app.com"
  image: cloudfoundry/korifi-api:latest

controllers:
  taskTTL: 5s
  image: cloudfoundry/korifi-controllers:latest

jobTaskRunner:
  jobTTL: 5s

kpackImageBuilder:
  builderRepository: localregistry-docker-registry.default.svc.cluster.local:30050/kpack-builder
  clusterStackBuildImage: paketobuildpacks/build:base-cnb
  clusterStackRunImage: paketobuildpacks/run:base-cnb
