global:
  defaultAppDomainName: vcap.me

api:
  apiServer:
    url: localhost
  image: cloudfoundry/korifi-api:latest
  packageRegistry:
    base: localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages

controllers:
  taskTTL: 5s
  image: cloudfoundry/korifi-controllers:latest

job-task-runner:
  image: cloudfoundry/korifi-job-task-runner:latest
  jobTTL: 5s

kpack-image-builder:
  image: cloudfoundry/korifi-kpack-image-builder:latest
  packageRegistry:
    base: localregistry-docker-registry.default.svc.cluster.local:30050/korifi-controllers/kpack/images

statefulset-runner:
  image: cloudfoundry/korifi-statefulset-runner:latest
