adminUserName: cf-admin

global:
  defaultAppDomainName: apps-127-0-0-1.nip.io
  generateIngressCertificates: true

api:
  apiServer:
    url: localhost
  image: cloudfoundry/korifi-api:latest
  packageRepository: localregistry-docker-registry.default.svc.cluster.local:30050/packages

controllers:
  taskTTL: 5s
  image: cloudfoundry/korifi-controllers:latest

job-task-runner:
  image: cloudfoundry/korifi-job-task-runner:latest
  jobTTL: 5s

kpack-image-builder:
  image: cloudfoundry/korifi-kpack-image-builder:latest
  dropletRepositoryPrefix: localregistry-docker-registry.default.svc.cluster.local:30050/droplets
  builderRepository: localregistry-docker-registry.default.svc.cluster.local:30050/kpack-builder
  clusterStackBuildImage: paketobuildpacks/build:base-cnb
  clusterStackRunImage: paketobuildpacks/run:base-cnb

statefulset-runner:
  image: cloudfoundry/korifi-statefulset-runner:latest
