adminUserName: cf-admin

global:
  defaultAppDomainName: vcap.me
  generateIngressCertificates: true

api:
  apiServer:
    url: localhost
  image: cloudfoundry/korifi-api:latest
  packageRepositoryPrefix: localregistry-docker-registry.default.svc.cluster.local:30050/sources
  packageRegistrySecret: image-registry-credentials

controllers:
  taskTTL: 5s
  image: cloudfoundry/korifi-controllers:latest

job-task-runner:
  image: cloudfoundry/korifi-job-task-runner:latest
  jobTTL: 5s

kpack-image-builder:
  image: cloudfoundry/korifi-kpack-image-builder:latest
  dropletRepositoryPrefix: localregistry-docker-registry.default.svc.cluster.local:30050/droplets
  builderRepository: localregistry-docker-registry.default.svc.cluster.local:30050/kpack-builder

statefulset-runner:
  image: cloudfoundry/korifi-statefulset-runner:latest
