{{- if .Values.global.generateIngressCertificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-api-ingress-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ .Values.apiServer.url }}
  dnsNames:
  - {{ .Values.apiServer.url }}
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: korifi-api-ingress-cert
{{- end }}
