apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: {{ .Values.namespace }}
  name: korifi-api-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - {{ .Values.apiServer.url }}
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ .Values.namespace }}
  name: korifi-api
spec:
  hosts:
  - {{ .Values.apiServer.url }}
  gateways:
  - korifi-api-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - {{ .Values.apiServer.url }}
    route:
    - destination:
        host: korifi-api-svc
        port:
          number: 443
