apiVersion: v1
kind: Service
metadata:
  annotations:
    projectcontour.io/upstream-protocol.tls: "443"
  labels:
    app: korifi-api
  name: korifi-api-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: web
    port: 443
    protocol: TCP
    targetPort: 9000
  selector:
    app: korifi-api
  type: ClusterIP

---
{{- if .Values.global.debug }}
apiVersion: v1
kind: Service
metadata:
  name: api-debug-port
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: debug-30052
      nodePort: 30052
      port: 30052
      protocol: TCP
      targetPort: 40000
  selector:
    app: korifi-api
  type: NodePort
{{- end }}
