name: Run Tests on PR

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '.*'

jobs:
  check-reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # The Go version to download (if necessary) and use.
      - name: Check for reference yaml drift
        run: |
          make build-reference
          git diff --exit-code

  run-envtest:
    needs: check-reference
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Run envtest
        run: make test
