serverURL: http://localhost
serverPort: 9000
rootNamespace: cf
defaultLifecycleConfig:
  type: buildpack
  stack: cflinuxfs3
  stagingMemoryMB: 1024
  stagingDiskMB: 1024
packageRegistryBase: gcr.io/cf-relint-greengrass/cf-k8s-controllers/kpack/beta
packageRegistrySecretName: image-registry-credentials
authEnabled: true
clusterBuilderName: cf-kpack-cluster-builder
